name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies with poetry
      run: |
        poetry install
        sweep
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest

