name: Pylint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: <desired_python_version>

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run pylint
        run: poetry run pylint --errors-only sweepai